### ISSUE TITLE
IDA Fails to load plugin

### ISSUE THREAD

**Issue by blxd** [lab313ru/messida#4]
Using the v1.5.3 32-bit plugin, IDA fails to load the plugin and gives the error "Wrong DBG_RESMOD_STEP_... bits". This occurs either when loading an existing database or when loading a new file. 

```
IDA Version: Starter 6.8.150428 (32-bit)
OS: Windows 10 Home
MESSIDA Version: 1.5.3 32-bit
```

**Comment by DrMefistO** [comment]
Hi,
Please give me screenshot of this error. And...
I think, there are some changes in DBG interface, and old interface is not compatible.
Could you try to build Messida by your own with 6.8 SDK? (If you will have some troubles with that just ask me).

**Comment by blxd** [comment]
Thanks for the reply. I will try recompiling it ... 

Here's a screenshot of the error, I started a new database and loaded a Game Genie rom.
<img width="943" alt="screen shot 2015-10-22 at 12 43 44" src="https://cloud.githubusercontent.com/assets/11062583/10664385/d67af062-78ba-11e5-9265-f1e5beba9eff.png">

**Comment by DrMefistO** [comment]
Hmm.
It shows that you're using v1.5 version, but not v1.5.3.

**Comment by blxd** [comment]
I used the messida_v1_5_3_x86.7z file from the latest release.

**Comment by DrMefistO** [comment]
Hmm.. Ok) So, it's my bug about version in log. Waiting for your building result.

**Comment by blxd** [comment]
Finally managed to get it loaded in to vs2013, mame builds build messida does not build. I am using the source from the 1.5.3 tag. 

```
4>------ Build started: Project: messida, Configuration: Release Win32 ------
4>  drivlist.c
4>  mame.c
4>  version.c
4>  debug.cpp
4>debug.cpp(970): error C2440: 'initializing' : cannot convert from 'int (__stdcall *)(thid_t)' to 'int (__stdcall *)(thid_t,resume_mode_t)'
4>          None of the functions with this name in scope match the target type
4>  dialog_utils.cpp
4>  nargv.c
4>  plugin.cpp
4>plugin.cpp(280): error C3867: 'debugger_t::registers': function call missing argument list; use '&debugger_t::registers' to create a pointer to member
4>plugin.cpp(280): error C2109: subscript requires array or pointer type
4>plugin.cpp(280): error C2228: left of '.name' must have class/struct/union
4>plugin.cpp(310): error C3867: 'debugger_t::registers': function call missing argument list; use '&debugger_t::registers' to create a pointer to member
4>plugin.cpp(310): error C2109: subscript requires array or pointer type
4>plugin.cpp(310): error C2228: left of '.name' must have class/struct/union
4>plugin.cpp(316): error C3867: 'debugger_t::registers': function call missing argument list; use '&debugger_t::registers' to create a pointer to member
4>plugin.cpp(316): error C2109: subscript requires array or pointer type
4>plugin.cpp(316): error C2228: left of '.name' must have class/struct/union
4>  vdp_ram.cpp
4>  Generating Code...
========== Build: 3 succeeded, 1 failed, 19 up-to-date, 0 skipped ==========
```

**Comment by DrMefistO** [comment]
I see...
They have changed some specifications. If you understand what these errors mean, you may fix them by yourself. If no, I l'll try to fix that for you. The main problem is that I have no SDK for IDA 6.8, and IDA v6.8 at all. So, all my fixes will be guessed on your output log.

**Comment by blxd** [comment]
In `debugger_t` they changed some previously reserved flag to resume_modes (https://www.hex-rays.com/products/ida/support/sdkdoc/structdebugger__t.html#a71ed80f2b468eb868a4c1cfcbe1d7493). Changing that to `DBG_RESMOD_STEP_INTO` appears to work :) The compile errors were easily fixable, they changed an array to a function and changed another method signature. I will submit a PR in a few days to fix it :)

**Comment by DrMefistO** [comment]
I could only make a separate branch for your commit. Because me and many other people doesn't have bought IDA v6.8, and they're using v6.6/v6.5 only.

**Comment by blxd** [comment]
There is the `IDD_INTERFACE_VERSION` macro defined in `idd.hpp` which I can use to change different versions of the function calls and flags with macros. What value is define for `IDD_INTERFACE_VERSION` in IDA6.6?

**Comment by DrMefistO** [comment]
#define         IDD_INTERFACE_VERSION   17

**Comment by blxd** [comment]
Yeah, it has to be a compile time difference. I had this sort of thing in mind - which is working with IDA68.
```C
#if IDD_INTERFACE_VERSION >= 19
static int idaapi thread_set_step(thid_t tid, resume_mode_t mode) // Run one instruction in the thread
{
	switch (mode)
	{
	case RESMOD_INTO:
		get_debugger()->single_step();
		break;

	case RESMOD_OVER:
		get_debugger()->single_step_over();
		break;

	case RESMOD_OUT:
		get_debugger()->single_step_out();
		break;
	}
	return 1;
}
#else
static int idaapi thread_set_step(thid_t tid) // Run one instruction in the thread
{
	return do_step(get_running_notification());
}
#endif
```

**Comment by DrMefistO** [comment]
Ok, I'll use it. Thank you.

**Comment by DrMefistO** [comment]
Or that fix is not whole fix?

**Comment by blxd** [comment]
Not the whole fix, I'll send a pull requests once I have ironed out the bugs :)

**Comment by lab313ru** [comment]
Updated to IDA 6.8 SDK. Closed.
